### ISSUE TITLE
ERROR: -nms option is deprecated

### ISSUE THREAD

**Issue by LeileiCui** [Steven-N-Hart/softsearch#1]
Dear Steven,

Tks a lot for your fantastic software. I have tied the SoftSearch.pl on my WGS data, the perl I used is v5.10.1, and the command and error as below:

COMMAND: 
perl SoftSearch.pl -b Bur_0_bur_PII.bam -f tair10_um_new.fa -o SoftSearch.test.vcf

ERROR:
Start Time : 2016-07-12 11:00:41
Writing results to SoftSearch.111.vcf
Use of uninitialized value $dist_To_Soft in concatenation (.) or string at /SAN/mottlab/heterosis/bin/4_SoftSearch/src/SoftSearch.pl line 107.
Usage = SoftSearch.pl -l 5 -q 20 -r 5 -d  -m 5 -s 6 -c  -b Bur_0_bur_PII.bam -f tair10_um_new.fa -o SoftSearch.test.vcf 

The mean insert size is 15407 +/- 558442 (sd)
The upper limit = 3366059
The lower limit = -3335245

Warning!! Given this insert size distribution, we can not call small indels.  No other data will be affected
Making SAM file of soft-clipped reads
Identifying soft-clipped regions that are at least 5 bp long 
Calling sides of soft-clips
Running Bam2pair.pl
Looking for discordant read pairs without requiring soft-clipping information

Looking for Discordant read pairs (and Unmated reads) without soft-clips

Bam2pair.pl Done

****\* ERROR: -nms option is deprecated. Please see the documentation for the -c and -o column operation options. *****
mergeBed file is empty.
No strucutral variants found

Q1: Could you please to help me check out what is going on with the error above? Or at least something different to try?
Q2: I also found two perl scripts "SoftSearch.pl" and "SoftSearch.multi.pl" under src folder, what's the different usage of these two scripts?  

Thanks in advance,
Leilei

**Comment by Steven-N-Hart** [comment]
It sounds like your BEDtools version is too recent.  This is a dependency that we used for getting the names of the overlapping segments.  Try reverting to an older version of BEDtools that does not call that error (e.g. v2.16.2).

The `SoftSearch.multi.pl` was a script I was working on to allow for multiple BAM file inputs, but I don't think it should be used.
